# Add name in language.framework format
name: java.springbootgradle

on:
  push:
    branches:
      - main
# Add name in language/framework format
    paths:
      - "java/springbootgradle/**"
      - "!**/README.md"
  pull_request:
    branches:
        - main

# Specify the required variables
env:
  DOCKERHUB_TAG: "${{ secrets.DOCKERHUB_USERNAME }}/springbootgradle"
  DOCKERFILE_PATH: java/springbootgradle

# No Changes needed below
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "${{ env.DOCKERFILE_PATH }}"
          push: true
          tags: "${{ env.DOCKERHUB_TAG }}:latest"      

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker.io/${{ env.DOCKERHUB_TAG }}:latest"
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'